# Generated by Django 3.1.4 on 2020-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='QueryImages')),
                ('debug', models.BooleanField()),
                ('shop', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
    ]
