# Generated by Django 3.1.4 on 2020-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerimageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerimageupload',
            name='shop',
            field=models.IntegerField(),
        ),
    ]
