# Generated by Django 3.1.4 on 2021-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.CharField(choices=[('www.koton.com', 'Koton'), ('www.lcwaikiki.com', 'Lcwaikiki'), ('www.boyner.com.tr', 'Boyner'), ('www.defacto.com.tr', 'Defacto'), ('www.trendyol.com', 'Trendyol'), ('www2.hm.com/tr_tr', 'Hm')], default='www.koton.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='item_pictures'),
        ),
    ]
