# Generated by Django 3.1.4 on 2021-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210125_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='image_url',
            field=models.CharField(default='sddsd', max_length=256),
            preserve_default=False,
        ),
    ]
