# Generated by Django 3.1.4 on 2021-02-10 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_scrapeditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryitem',
            name='color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='queryitem',
            name='label',
            field=models.CharField(choices=[('www.koton.com', 'Koton'), ('www.lcwaikiki.com', 'Lcwaikiki'), ('www.boyner.com.tr', 'Boyner'), ('www.defacto.com.tr', 'Defacto'), ('www.trendyol.com', 'Trendyol'), ('www2.hm.com/tr_tr', 'Hm')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='queryitem',
            name='texts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='label',
            field=models.CharField(choices=[('www.koton.com', 'Koton'), ('www.lcwaikiki.com', 'Lcwaikiki'), ('www.boyner.com.tr', 'Boyner'), ('www.defacto.com.tr', 'Defacto'), ('www.trendyol.com', 'Trendyol'), ('www2.hm.com/tr_tr', 'Hm')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='image_url',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='url',
            field=models.URLField(max_length=256),
        ),
    ]
