# Generated by Django 3.1.4 on 2021-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20210305_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryitem',
            name='label',
            field=models.CharField(choices=[('short_sleeved_shirt', 'Short Sleeved Shirt'), ('long_sleeved_shirt', 'Long Sleeved Shirt'), ('short_sleeved_outwear', 'Short Sleeved Outwear'), ('long_sleeved_outwear', 'Long Sleeved Outwear'), ('vest', 'Vest'), ('sling', 'Sling'), ('shorts', 'Shorts'), ('trousers', 'Trousers'), ('skirt', 'Skirt'), ('short_sleeved_dress', 'Short Sleeved Dress'), ('long_sleeved_dress', 'Long Sleeved Dress'), ('vest_dress', 'Vest Dress'), ('sling_dress', 'Sling Dress'), ('None', 'None')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='label',
            field=models.CharField(choices=[('Bra', 'Bra'), ('Briefs', 'Briefs'), ('Capris', 'Capris'), ('Casual Shoes', 'Casualshoes'), ('Dresses', 'Dresses'), ('Flats', 'Flats'), ('Flip Flops', 'Flipflops'), ('Formal Shoes', 'Formalshoes'), ('Heels', 'Heels'), ('Innerwear Vests', 'Innervests'), ('Jackets', 'Jackets'), ('Jeans', 'Jeans'), ('Kurtas', 'Kurtas'), ('Kurtis', 'Kurtis'), ('Leggings', 'Leggings'), ('Night suits', 'Nightsuits'), ('Nightdress', 'Nightdress'), ('Sandals', 'Sandals'), ('Sarees', 'Sarees'), ('Shirts', 'Shirts'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Sports Shoes', 'Sportsshoes'), ('Sweaters', 'Sweaters'), ('Sweatshirts', 'Sweatshirts'), ('Tops', 'Tops'), ('Track Pants', 'Trackpants'), ('Trousers', 'Trousers'), ('Trunk', 'Trunk'), ('Tshirts', 'Tshirts'), ('Tunics', 'Tunics'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
