# Generated by Django 3.1.4 on 2021-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210415_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='label',
            field=models.CharField(choices=[('short_sleeved_shirt', 'Short Sleeved Shirt'), ('long_sleeved_shirt', 'Long Sleeved Shirt'), ('short_sleeved_outwear', 'Short Sleeved Outwear'), ('long_sleeved_outwear', 'Long Sleeved Outwear'), ('vest', 'Vest'), ('sling', 'Sling'), ('shorts', 'Shorts'), ('trousers', 'Trousers'), ('skirt', 'Skirt'), ('short_sleeved_dress', 'Short Sleeved Dress'), ('long_sleeved_dress', 'Long Sleeved Dress'), ('vest_dress', 'Vest Dress'), ('sling_dress', 'Sling Dress'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
