version: '3'
services:
  db:
    image: postgres
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - db
  backend-shell:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ..:/code
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
