version: '3.6'
services:
  db:
    environment:
      POSTGRES_USER: outletter
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  backend:
    command: python manage.py runserver 0:8000
    entrypoint: /code/docker/entrypoint.sh
    volumes:
      - ..:/code
    ports:
      - 8000:8000
