version: '3'
services:
  db:
    image: postgres
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - db
  backend-shell:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ..:/code
