# Generated by Django 3.1.4 on 2021-04-19 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0007_auto_20210415_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('rel_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', related_query_name='user_likes', to='item.scrapeditem', verbose_name='Item Like')),
                ('rel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', related_query_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='User Like')),
            ],
            options={
                'verbose_name': 'Like',
                'ordering': ['-created_at'],
            },
        ),
    ]
