# Generated by Django 3.1.4 on 2021-04-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='preference',
        ),
    ]
